<?php

namespace Jacquet\TrocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjetTrocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetTrocRepository extends EntityRepository
{
}
