<?php

namespace Jacquet\TrocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrocRepository extends EntityRepository
{
}
