parameters:
#    jacquet_utilisateur.example.class: Jacquet\UtilisateurBundle\Example

services:
#    jacquet_utilisateur.example:
#        class: %jacquet_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    jacquet_user.registration.form.type:
        class: Jacquet\UtilisateurBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jacquet_user_registration }